### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 () /broadcasting/auth

### ISSUE THREAD

**Issue by JamesThanna** [tastyigniter/ti-ext-broadcast#2]
Hey, 

I've tried to find the cause myself for a few days but really stuck to why this is happening. I've installed this on both v2 and v3 beta but seeing the same issue with both of these. 

I've complete a fresh install of the software with demo content and then installed all the required extensions and also done this with the set up wizard.  Once I add the extension and add the API details. 

I'm then seeing a 403 across the front-end of the website in the console.  I can't seem to find the cause of the problem I've tripled checked the the details being added to `System > Settings > Broadcast Events settings`.  

I'm stuck to why this happening. I've tried on 3 different environments with multiple installs and also tried going back and using a different version of broadcast both seem to generate the error. 

In turn I think this affecting the other extensions such as order approval from pinging when an order comes in.
`Request URL: https://domainname.com/broadcasting/auth
Request Method: POST
Status Code: 403 
Remote Address: 
Referrer Policy: strict-origin-when-cross-origin
cache-control: no-cache, private
content-encoding: br
content-length: 504
content-type: text/html; charset=UTF-8
date: Mon, 15 Mar 2021 12:17:10 GMT
server: LiteSpeed
set-cookie: tastyigniter_session=eyJpdiI6ImJlTWFhaXpLQ052NGJER01cL0poYldnPT0iLCJ2YWx1ZSI6InhQNUVMZnY5XC9sV3kydTFQUFZuNEZRNG1mYmFMMEVBZDBtSHd0Y3hZK3ZvZldGckpNU1JvSXdVeDIzd1d4bHoyaFpQc2FBaHRVMHZyNDZGNmpGZ244ajQ4UmxDb1wvVmZsMjlMUzRYdGUwUWxhT0VMMVZtYlU4S2hsOWFFM1l6RkMiLCJtYWMiOiI2ODNhMGIxOWU5NDMyNjQwN2Y2YjBiMTM1YTg1MzUwZjZmYjZmMWJmN2IzZmE4M2RhNDdkMjQxYzA1YjRkZjIzIn0%3D; expires=Mon, 15-Mar-2021 14:17:10 GMT; Max-Age=7200; path=/; httponly; secure
vary: Accept-Encoding,User-Agent`

**Comment by ryanmitchell** [comment]
It seems to be a bug in Litespeed another user reported the same thing - have you tried using Nginx or apache?

**Comment by JamesThanna** [comment]
Moved to Apache and it works it was me who reported it too you 👌

**Comment by ryanmitchell** [comment]
👍
