### ISSUE TITLE
[Bug]: Settings can't be saved as optional fields are required

### ISSUE THREAD

**Issue by ryanmitchell** [tastyigniter/ti-ext-broadcast#6]
### What happened?

Try to save settings without using laravel web sockets (ie what used to be the default).

You are told host, port and scheme are required.

Tried to update to required_if for a PR but that didnt work either

### What did you expect to happen?

Them not to be required as they are optional.

### Version

Other (please detail)

### What browser are you seeing the problem on?

Safari

**Comment by sampoyigi** [comment]
required_if worked for me.. Extension patched and updated :)

**Comment by ryanmitchell** [comment]
Cool :)
